name: when_pickup
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks:
  jiffy:
  flutter_native_splash:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:



flutter:
  uses-material-design: true



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: images/shrug.png
  min_sdk_android: 23
  remove_alpha_ios: true

flutter_native_splash:
  color: "#0057BA"
  image: images/shrug.png
  android_12:
    color: "#0057BA"
